### ISSUE TITLE
Can create session with no user ID

### ISSUE THREAD

**Issue by Rory-Reid** [cdcaskey/Clothes-Line#4]
Hello,

I made a session but forgot to type in my name. When I clicked "Create Session" the server apologised.

Session URL path: `/session/028269/` 

Screenshot:
<img width="576" alt="image" src="https://user-images.githubusercontent.com/8151382/154013439-26cc0fe0-9811-429a-a6e8-9517b25a5544.png">

**Comment by cdcaskey** [comment]
You break it, you buy it

**Comment by cdcaskey** [comment]
Dear Lord, what a sad little life, @RoryRoberts. You ruined my night, completely, so you could have the issue, but I hope now you spend the time getting some lessons in grace and decorum because you have all the grace of a reversing dump truck without any tyres on.

**Comment by cdcaskey** [comment]
Oh yeah, also I fixed it
